version: '3.1'
services:
    mc:
        image: mirth-container:latest
        stdin_open: true # docker run -i
        tty: true
        user: 1000:1000
        ports:
            - "8443:8443"
        networks:
            mirth:
                ipv4_address: 10.5.0.6
        volumes:
            - ./appdata:/opt/connect/appdata
        environment:
            - MP_DATABASE=postgres
            - MP_DATABASE_URL=jdbc:postgresql://10.5.0.5:5432/mirthtest
            - MP_DATABASE_USERNAME=mirthtest
            - MP_DATABASE_PASSWORD=mirthtest
            - MP_KEYSTORE_KEYPASS=test
            - MP_KEYSTORE_STOREPASS=test
            - EXTENSIONS_DOWNLOAD=https://innovar-userdocuments.s3.us-east-2.amazonaws.com/mirth_plugins/ssl-settings/ssl-settings-4.5.0.zip,https://innovar-userdocuments.s3.us-east-2.amazonaws.com/mirth_plugins/channelHistory/innovarhealthcare-channelHistory-4.5.0.zip
    
    postgres:
        image: postgres:14-alpine
        networks:
            mirth:
                ipv4_address: 10.5.0.5
        ports:
            - 5432:5432
        # volumes:
        #     - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=mirthtest
            - POSTGRES_USER=mirthtest
            - POSTGRES_DB=mirthtest

networks:
    mirth:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1