version: '3.1'
services:
    bl:
        image: innovarhealthcare/bridgelink:4.5.3
        stdin_open: true # docker run -i
        tty: true
        user: 1000:1000
        ports:
            - "8443:8443"
        networks:
            bridgelink:
                ipv4_address: 10.5.0.6
        volumes:
            - ./appdata:/opt/bridgelink/appdata
        secrets:
        - source: blserver_vmoptions
        environment:
            - MP_DATABASE=postgres
            - MP_DATABASE_URL=jdbc:postgresql://10.5.0.5:5432/bridgelinkdb
            - MP_DB_SCHEMA=bridgelinkdb
            - MP_DATABASE_USERNAME=bridgelinktest
            - MP_DATABASE_PASSWORD=bridgelinktest
            - MP_DATABASE_DBNAME=bridgelinkdb
            - SERVER_ID=xxxxxx-xxxxxxx-xxxxxxxxxxx
            - MP_KEYSTORE_KEYPASS=bridgelinkKeystore
            - MP_KEYSTORE_STOREPASS=bridgelinkKeypass

    postgres:
        image: postgres:14-alpine
        networks:
            bridgelink:
                ipv4_address: 10.5.0.5
        ports:
            - 5432:5432
        # volumes:
        #     - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=bridgelinktest
            - POSTGRES_USER=bridgelinktest
            - POSTGRES_DB=bridgelinkdb
secrets:
    mirth_properties:
        file: appdata/secret.properties
    blserver_vmoptions:
        file: appdata/custom_blserver.vmoptions
networks:
    bridgelink:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1