services:
  bl:
    image: innovarhealthcare/bridgelink:4.5.4
    stdin_open: true
    tty: true
    user: 1000:1000
    ports:
      - "8443:8443"
    volumes:
      - ./appdata:/opt/bridgelink/appdata
    secrets:
      - blserver_vmoptions
    environment:
      MP_DATABASE: postgres
      MP_DATABASE_URL: jdbc:postgresql://postgres:5432/bridgelinkdb
      MP_DATABASE_USERNAME: bridgelinktest
      MP_DATABASE_PASSWORD: bridgelinktest
      SERVER_ID: 7d760af2-680a-4a19-b9a2-c4685df61ebc
      MP_KEYSTORE_KEYPASS: bridgelinkKeystore
      MP_KEYSTORE_STOREPASS: bridgelinkKeypass
      MP_CONFIGURATIONMAP_LOCATION: database
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bridgelinktest
      POSTGRES_USER: bridgelinktest
      POSTGRES_DB: bridgelinkdb

secrets:
  blserver_vmoptions:
    file: appdata/custom_blserver.vmoptions