version: '3.1'
services:
    bl:
        image: bridgelink-container:latest
        stdin_open: true # docker run -i
        tty: true
        user: 1000:1000
        ports:
            - "8443:8443"
        networks:
            bridgelink:
                ipv4_address: 10.5.0.6
        volumes:
            - ./appdata:/opt/bridgelink/appdata
        environment:
            - MP_DATABASE=postgres
            - MP_DATABASE_URL=jdbc:postgresql://10.5.0.5:5432/mirthdb
            - MP_DB_SCHEMA=mirthdb
            - MP_DATABASE_USERNAME=mirthtest
            - MP_DATABASE_PASSWORD=mirthtest
            - MP_DATABASE_DBNAME=mirthdb
            - SERVER_ID=7d760af2-680a-4a19-b9a2-c4685df61ebc
            - MP_VMOPTIONS=512
            - CUSTOM_JARS_DOWNLOAD=https://innovar-awsmarketplace.s3.us-east-1.amazonaws.com/AWS_Jar/docker-test-jar.zip
 
    postgres:
        image: postgres:14-alpine
        networks:
            bridgelink:
                ipv4_address: 10.5.0.5
        ports:
            - 5432:5432
        # volumes:
        #     - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=mirthtest
            - POSTGRES_USER=mirthtest
            - POSTGRES_DB=mirthdb

networks:
    bridgelink:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1