{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
    release: {{ .Release.Name }}
{{- end }}