{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bridgelink-postgres
  labels:
    app: postgres
    {{- include "bridgelink.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
{{- end }}