{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bridgelink.fullname" . }}-postgres
  labels:
    {{- include "bridgelink.postgresLabels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "bridgelink.postgresSelectorLabels" . | nindent 4 }}
{{- end }}