{{- if .Values.webadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bridgelink.fullname" . }}-webadmin
  labels:
    {{- include "bridgelink.webadminLabels" . | nindent 4 }}
  {{- with .Values.webadmin.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- include "bridgelink.serviceSpec" .Values.webadmin.service | nindent 2 }}
  ports:
    - port: {{ .Values.webadmin.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "bridgelink.webadminSelectorLabels" . | nindent 4 }}
{{- end }}
